version: '3.1'
services:
    jenkins:
        env_file:
          - .env
        build:
            context: ./
            # args:
            #     HOST_UID: ${JENKINS_HOST_UID}
            #     HOST_GID: ${DOCKER_HOST_GID}
        restart: unless-stopped
        environment:
          - "JAVA_OPTS=-Xmx2g -Xms1G"
        volumes:
            - ${HOST_DOCKER_SOCKET}:/var/run/docker.sock
            - ${HOST_JENKINS_VOLUME}:/var/jenkins_home
        ports:
            - ${HOST_PORT}:${CONTAINER_PORT}
            - "50000:50000"